import "@/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <div className="flex justify-center items-center w-full">
          {children}
        </div>
      </body>
    </html>
  );
}
